//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskGrapher
{
    using System;
    using System.Collections.Generic;
    
    public partial class men_tte
    {
        public string tte_tktc { get; set; }
        public decimal tte_seq3 { get; set; }
        public Nullable<decimal> tte_rank { get; set; }
        public string tte_step { get; set; }
        public string tte_page { get; set; }
        public string tte_name { get; set; }
        public string tte_desc { get; set; }
        public string tte_iuse { get; set; }
        public string tte_ctrl { get; set; }
        public string tte_link { get; set; }
        public string tte_prbb { get; set; }
        public string tte_disp { get; set; }
        public string tte_type { get; set; }
        public string tte_slgc { get; set; }
        public string tte_srlc { get; set; }
        public string tte_conc { get; set; }
        public string tte_cops { get; set; }
        public string tte_pogc { get; set; }
        public string tte_podc { get; set; }
        public string tte_ttuc { get; set; }
        public string tte_prac { get; set; }
        public string tte_oper { get; set; }
        public string tte_abpc { get; set; }
        public string tte_uduc { get; set; }
        public string tte_urla { get; set; }
        public string tte_nxtf { get; set; }
        public string tte_nxtt { get; set; }
        public string tte_csrl { get; set; }
        public string tte_hlpf { get; set; }
        public string tte_appf { get; set; }
        public string tte_keep { get; set; }
        public string tte_appt { get; set; }
        public string tte_nxts { get; set; }
        public string tte_errs { get; set; }
        public string tte_prec { get; set; }
        public string tte_oths { get; set; }
        public string tte_relo { get; set; }
        public string tte_btip { get; set; }
        public string tte_ntip { get; set; }
        public string tte_rawm { get; set; }
        public string tte_htvc { get; set; }
        public string tte_tblt { get; set; }
        public string tte_parm { get; set; }
        public string tte_head { get; set; }
        public string tte_help { get; set; }
        public string tte_html { get; set; }
        public string TTE_FOOT { get; set; }
    }
}
