//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskGrapher
{
    using System;
    using System.Collections.Generic;
    
    public partial class men_tec
    {
        public string tec_tktc { get; set; }
        public decimal tec_ttes { get; set; }
        public decimal tec_seq2 { get; set; }
        public string tec_desc { get; set; }
        public string tec_step { get; set; }
        public string tec_iuse { get; set; }
        public Nullable<decimal> TEC_RANK { get; set; }
    }
}
