//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskGrapher
{
    using System;
    using System.Collections.Generic;
    
    public partial class men_tkt
    {
        public string tkt_code { get; set; }
        public string tkt_snam { get; set; }
        public string tkt_name { get; set; }
        public string tkt_iuse { get; set; }
        public Nullable<decimal> tkt_wght { get; set; }
        public string tkt_link { get; set; }
        public string tkt_rpya { get; set; }
        public string tkt_dela { get; set; }
        public string tkt_mstc { get; set; }
        public string tkt_from { get; set; }
        public string tkt_tref { get; set; }
        public string tkt_actn { get; set; }
        public string tkt_eref { get; set; }
        public string tkt_subj { get; set; }
        public string tkt_clup { get; set; }
        public string tkt_stab { get; set; }
        public string tkt_htvc { get; set; }
        public string tkt_audf { get; set; }
        public string tkt_bart { get; set; }
        public string tkt_mst1 { get; set; }
        public string tkt_mst2 { get; set; }
        public Nullable<System.DateTime> tkt_cred { get; set; }
        public Nullable<System.DateTime> tkt_updd { get; set; }
        public string tkt_udf1 { get; set; }
        public string tkt_udf2 { get; set; }
        public string tkt_udf3 { get; set; }
        public string tkt_udf4 { get; set; }
        public string tkt_udf5 { get; set; }
        public string tkt_udf6 { get; set; }
        public string tkt_udf7 { get; set; }
        public string tkt_udf8 { get; set; }
        public string tkt_udf9 { get; set; }
        public string tkt_udfa { get; set; }
        public string tkt_udfb { get; set; }
        public string tkt_udfc { get; set; }
        public string tkt_udfd { get; set; }
        public string tkt_udfe { get; set; }
        public string tkt_udff { get; set; }
        public string tkt_udfg { get; set; }
        public string tkt_udfh { get; set; }
        public string tkt_udfi { get; set; }
        public string tkt_udfj { get; set; }
        public string tkt_udfk { get; set; }
        public string tkt_mprd { get; set; }
        public string tkt_bar { get; set; }
        public string tkt_text { get; set; }
        public string tkt_htmo { get; set; }
        public string tkt_htmc { get; set; }
        public string tkt_html { get; set; }
    }
}
