//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskGrapher
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SITSDEVEntities : DbContext
    {
        public SITSDEVEntities()
            : base("name=SITSDEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<men_tec> men_tec { get; set; }
        public virtual DbSet<men_tkt> men_tkt { get; set; }
        public virtual DbSet<men_tte> men_tte { get; set; }
    }
}
